export const SCREEN_WIDTH = 1600
export const SCREEN_HEIGHT = 1200
export const ROTATION_SPEED = 0.5 * Math.PI
export const ROTATION_SPEED_DEGREES = Phaser.Math.RadToDeg(ROTATION_SPEED)
export const TOLERANCE = 0.02 * ROTATION_SPEED
export const SPEED = 100
export const RELOAD_TIME = 4000
export const DAMAGE = 10
export const REPAIRING_SPEED = 4000
export const REPAIR_HEALTH = 40